[package]
name = "elevenlabs_rs"
version = "0.3.2"
description = "A lib crate for ElevenLabs"
authors = ["rwxbytes <rwxbytes@proton.me>"]
license = "MIT"
edition = "2021"
readme = "README.md"
repository = "https://github.com/rwxbytes/elevenlabs_rs"
keywords = ["elevenlabs", "tts", "text-to-speech", "voice-clone", "ai"]

exclude = [
  ".idea",
  "/src/endpoints/conversational_ai.rs",
  "/src/utils/audio_helpers.rs",
  "/src/convai_client.rs",
]


[dependencies]
async-stream = "0.3.5"
base64 = "0.22.1"
bytes = "1.4.0"
futures-channel = "0.3.30"
futures-util = "0.3.28"
reqwest = { version = "0.12.5", features = ["stream", "json", "multipart"] }
rodio = { version = "0.17.1", optional = true }
serde = { version = "1.0.173", features = ["derive"] }
serde_json = "1.0.103"
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["full"] }
tokio-tungstenite = { version = "0.23.0", features = ["native-tls"] }

[features]
default = ["playback"]
playback = ["dep:rodio"]
# Enable rustls for TLS support
rustls = ["reqwest/rustls-tls-native-roots"]
# Enable rustls and webpki-roots
rustls-webpki-roots = ["reqwest/rustls-tls-webpki-roots"]
# Enable native-tls for TLS support
native-tls = ["reqwest/native-tls"]
# Remove dependency on OpenSSL
native-tls-vendored = ["reqwest/native-tls-vendored"]

[dev-dependencies]
twilio = "1.1.0"
axum = { version = "0.7.5", features = ["ws"] }
async-openai = "0.23.3"
dasp = { version = "0.11.0", features = [
  "signal",
  "interpolate-linear",
  "interpolate",
  "slice",
] }
cpal = "0.15.3"
tokio-stream = "0.1.16"
bytemuck = "1.16.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = 'z'

[[example]]
name = "basic_twilio"
path = "examples/basic_twilio.rs"

[[example]]
name = "websocket_openai"
path = "examples/websocket_openai.rs"

[[example]]
name = "pronunciation_dictionaries"
path = "examples/pronunciation_dictionaries.rs"

[[example]]
name = "twilio_openai"
path = "examples/twilio_openai.rs"
